### ISSUE TITLE
Lite skeptisk till namngivningen, ser ut som man tar bort/lägger till tabeller

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [Saud0227/ms_inventory#1]
https://github.com/Saud0227/ms_inventory/blob/a94b2fca62eb81ff008d8e96aaaee2fcc055e6cf/src/db.rb#L31-L41

**Comment by Saud0227** [comment]
[Fix](https://github.com/Saud0227/ms_inventory/commit/3460674bc04a2d44d16cd2a1a009c94d1ab34247)
